modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="samhackers_command_gui"
version="1.0.0"
displayName="SamHacker's Command GUI"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="acer, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.samhackers_command_gui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



